### ISSUE TITLE
How did you handle invalid masks while evaluating on SSCBench-KITTI360

### ISSUE THREAD

**Issue by haiphamcse** [ahayler/s4c#2]
Hi there, loved your work. I just loaded your preprocessed GT for KITTI360 and noticed that you're still using the invalid mask from SSC (which covers the entire skies), did you noticed weird artifacts for MonoScene while training with these masks?

![image](https://github.com/ahayler/s4c/assets/76871780/d10a0e95-16f2-4fb3-bfbb-531def2bb7ba)

**Comment by ahayler** [comment]
Hi @haiphamcse, thank you for interest in our work.
S4C does not train on any 3D ground truth. The 3D data we provide is purely for evaluation purposes. Because of this, we use the data from the SSCBench paper, but correctly preprocess it to make it easier to work with (for us and other researchers). In particular, the invalid masks provided are exactly the same as in SSCBench. As you have realized, these masks are far from perfect. Therefore, we did add some additional invalids (below street level) in our evaluation script. We did not remove any invalids during evaluation. More details can be found in the additional material of the S4C paper.
As SSCBench does unfortunately not provide any model checkpoints, we also had to try to reproduce their reported results. We managed to this for all but the VoxFormer paper, which we were therefore unable to report results for (as we have to run the evaluate the trained model with the additional invalids). We trained all these models with the correctly pre-processed 3D data (this does not include our additional invalids). During our limited qualitative evaluation of our results on MonoScene (you can see some examples in the video and paper plots), I did not see any weird artefacts (within the field of view of the camera). The quantitive evaluation also matched the results reported in the SSCBench paper.

**Comment by haiphamcse** [comment]
Hi there, thank you for the quick reply. So just to clarify, you still keep the original invalid masks from SSCBench while training 3D baselines (MonoScene, LMSCNet) but while evaluating you add an extra mask under the drivable surface?

**Comment by ahayler** [comment]
Exactly, we wanted to replicate the model checkpoints from SSCBench. For more details please refer to the additional material.
