### ISSUE TITLE
About the removal of non-FOV areas in visualization

### ISSUE THREAD

**Issue by PhilipRS892** [ahayler/s4c#9]
Hey! love your excellent work!

I have a visual question. When I used the [script](https://github.com/ahayler/s4c/blob/main/scripts/benchmarks/sscbench/generate_ply_sequence.py)  you provided to generate visual sequences, I found that no matter how I set the variable "PLY_ONLY_FOV", the final visual structure would contain non-FOV regions. May I ask how I should remove them? Although I know you are not responsible for maintaining this part, I really hope to get your guidance!!!

With best wishes!

pute

<img width="1067" alt="image" src="https://github.com/user-attachments/assets/5b65dcb7-f896-4fd3-aadf-50559382edbc">

**Comment by ahayler** [comment]
Hey,
I am pretty sure that the issue is somewhere before `save_as_voxel_ply` is called. The file you linked should be fairly easy to debug. I leave you with some ideas on how I would approach debugging this:

1. Set the `fov_mask` to all 0s and see if you get an empty output. If not, clearly the mask isn't applied correctly.
2. Else, probably the mask is wrong. Try visualizing just the mask (just give it a random class) and see if it looks as expected (My hunch would be that this is the issue).

I sadly don't have the time to look into this (and further issues regarding visualization) myself.

All the best,
Adrian
